# Generated by Django 4.2.1 on 2023-05-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Consultante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=40)),
                ("motivo", models.TextField(max_length=100)),
                ("telefono", models.IntegerField()),
                ("mail", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Paciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=40)),
                ("edad", models.IntegerField()),
                ("telefono", models.IntegerField()),
                ("mail", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Terapeuta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=40)),
                ("edad", models.IntegerField()),
                ("precioSesion", models.IntegerField()),
                ("especializacion", models.TextField(max_length=100)),
                ("matricula", models.IntegerField()),
                ("telefono", models.IntegerField()),
                ("mail", models.EmailField(max_length=254)),
            ],
        ),
    ]
