# Generated by Django 4.2.1 on 2023-05-28 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("AppTerapia", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paciente",
            name="creador",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="consultante",
            name="motivo",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="terapeuta",
            name="especializacion",
            field=models.CharField(max_length=40),
        ),
    ]
